[tool.pyflow]
name = "kohtaaminen"
py_version = "3.8"
version = "2021.11.14"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
